version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: makerworks
      POSTGRES_PASSWORD: makerworks
      POSTGRES_DB: makerworks
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  backend:
    build: ../backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ../backend:/app
      - ${HOST_UPLOADS_DIR:-../uploads}:/data/uploads
      - ${HOST_THUMBNAILS_DIR:-../thumbnails}:/data/thumbnails
      - ${HOST_MODELS_DIR:-../models}:/data/models
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
  worker:
    build: ../backend
    command: rq worker
    volumes:
      - ../backend:/app
      - ${HOST_UPLOADS_DIR:-../uploads}:/data/uploads
      - ${HOST_THUMBNAILS_DIR:-../thumbnails}:/data/thumbnails
      - ${HOST_MODELS_DIR:-../models}:/data/models
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - redis
  frontend:
    build: ../frontend
    command: npm run dev -- --host
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  postgres-data:
  redis-data:
